// Copyright 2026 The uTLS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package tls

import (
	"bytes"
	"crypto/fips140"
	"crypto/mldsa"
	"encoding/hex"
	"fmt"
	"net"
	"os"
	"reflect"
	"slices"
	"sort"
	"strings"
	"testing"
)

// This parser is deliberately independent of Fingerprinter: comparing the
// captured browser bytes against generated bytes must not hide a parser bug.
// Only extension permutation, GREASE codepoints, ephemeral public keys, and
// GREASE ECH randomness are normalized. Ordered capability lists and trust
// anchor IDs retain their original order and bytes.
type chrome155WireHello struct {
	Version            uint16
	RandomLength       int
	SessionIDLength    int
	CipherSuites       []uint16
	CompressionMethods []byte
	Extensions         map[uint16][]string
}

type chrome155Reader struct {
	t     *testing.T
	b     []byte
	label string
}

func (r *chrome155Reader) take(n int) []byte {
	r.t.Helper()
	if n < 0 || n > len(r.b) {
		r.t.Fatalf("%s: truncated field: need %d bytes, have %d", r.label, n, len(r.b))
	}
	b := r.b[:n]
	r.b = r.b[n:]
	return b
}

func (r *chrome155Reader) number(n int) int {
	r.t.Helper()
	v := 0
	for _, b := range r.take(n) {
		v = v<<8 | int(b)
	}
	return v
}

func (r *chrome155Reader) vector(n int) []byte {
	r.t.Helper()
	return r.take(r.number(n))
}

func (r *chrome155Reader) end() {
	r.t.Helper()
	if len(r.b) != 0 {
		r.t.Fatalf("%s: %d trailing bytes", r.label, len(r.b))
	}
}

func chrome155NormalizeGREASE(v uint16) uint16 {
	if isGREASEUint16(v) {
		return GREASE_PLACEHOLDER
	}
	return v
}

func chrome155Uint16s(t *testing.T, b []byte) []uint16 {
	t.Helper()
	if len(b)%2 != 0 {
		t.Fatalf("odd uint16 vector length: %d", len(b))
	}
	out := make([]uint16, len(b)/2)
	for i := range out {
		out[i] = chrome155NormalizeGREASE(uint16(b[2*i])<<8 | uint16(b[2*i+1]))
	}
	return out
}

func chrome155NormalizeExtension(t *testing.T, id uint16, body []byte) string {
	t.Helper()
	r := chrome155Reader{t, body, fmt.Sprintf("extension %#04x", id)}
	var value string
	switch id {
	case 10, 13: // supported_groups, signature_algorithms
		value = fmt.Sprint(chrome155Uint16s(t, r.vector(2)))
	case 43: // supported_versions
		value = fmt.Sprint(chrome155Uint16s(t, r.vector(1)))
	case 51: // key_share
		shares := chrome155Reader{t, r.vector(2), "key_share entries"}
		var entries []string
		for len(shares.b) > 0 {
			group := uint16(shares.number(2))
			key := shares.vector(2)
			entry := fmt.Sprintf("%04x/%d", chrome155NormalizeGREASE(group), len(key))
			if isGREASEUint16(group) {
				entry += "/" + hex.EncodeToString(key)
			}
			entries = append(entries, entry)
		}
		value = strings.Join(entries, ",")
	case 0xfe0d: // GREASE encrypted_client_hello
		outer, kdf, aead := r.number(1), r.number(2), r.number(2)
		r.take(1) // randomized config_id
		enc, payload := r.vector(2), r.vector(2)
		if outer != 0 || !slices.Contains([]int{144, 176, 208, 240}, len(payload)) {
			t.Fatalf("unexpected GREASE ECH shape: outer=%d, payload length=%d", outer, len(payload))
		}
		value = fmt.Sprintf("%d/%d/%d/enc=%d/payload=144,176,208,240", outer, kdf, aead, len(enc))
	case 0xca34: // trust_anchors
		ids := chrome155Reader{t, r.vector(2), "trust anchor IDs"}
		for len(ids.b) > 0 {
			if len(ids.vector(1)) == 0 {
				t.Fatal("empty trust anchor ID in fixture")
			}
		}
		value = hex.EncodeToString(body)
	default:
		value = hex.EncodeToString(r.take(len(r.b)))
	}
	r.end()
	return value
}

func chrome155ParseWire(t *testing.T, data []byte) (chrome155WireHello, []uint16, map[uint16][]byte) {
	t.Helper()
	r := chrome155Reader{t, data, "ClientHello"}
	if len(data) > 0 && data[0] == byte(recordTypeHandshake) {
		if r.number(1) != int(recordTypeHandshake) || r.number(2) != int(VersionTLS10) {
			t.Fatal("unexpected ClientHello TLS record header")
		}
		record := r.vector(2)
		r.end()
		r = chrome155Reader{t, record, "ClientHello handshake"}
	}
	if r.number(1) != 1 {
		t.Fatal("fixture is not a ClientHello")
	}
	body := r.vector(3)
	r.end()
	r = chrome155Reader{t, body, "ClientHello body"}
	version := uint16(r.number(2))
	random := r.take(32)
	sid := r.vector(1)
	ciphers := chrome155Uint16s(t, r.vector(2))
	compression := bytes.Clone(r.vector(1))
	extensions := r.vector(2)
	r.end()
	out := chrome155WireHello{version, len(random), len(sid), ciphers, compression, make(map[uint16][]string)}
	r = chrome155Reader{t, extensions, "ClientHello extensions"}
	seen, raw := make(map[uint16]bool), make(map[uint16][]byte)
	var order []uint16
	for len(r.b) > 0 {
		id := uint16(r.number(2))
		body := r.vector(2)
		if seen[id] {
			t.Fatalf("duplicate extension %#04x", id)
		}
		seen[id] = true
		raw[id] = bytes.Clone(body)
		normalizedID := chrome155NormalizeGREASE(id)
		order = append(order, normalizedID)
		out.Extensions[normalizedID] = append(out.Extensions[normalizedID], chrome155NormalizeExtension(t, id, body))
	}
	for _, values := range out.Extensions {
		sort.Strings(values) // distinguish the two GREASE bodies independently of their values
	}
	return out, order, raw
}

func chrome155Fixture(t *testing.T) []byte {
	t.Helper()
	text, err := os.ReadFile("testdata/chrome155_clienthello.hex")
	if err != nil {
		t.Fatal(err)
	}
	data, err := hex.DecodeString(strings.Join(strings.Fields(string(text)), ""))
	if err != nil {
		t.Fatal(err)
	}
	return data
}

func chrome155FixtureServerName(t *testing.T, raw map[uint16][]byte) string {
	t.Helper()
	r := chrome155Reader{t, raw[0], "server_name"}
	names := chrome155Reader{t, r.vector(2), "server_name list"}
	r.end()
	if names.number(1) != 0 {
		t.Fatal("fixture SNI is not a host name")
	}
	name := string(names.vector(2))
	names.end()
	return name
}

func chrome155Build(t *testing.T, id ClientHelloID, serverName string, spec *ClientHelloSpec) *UConn {
	t.Helper()
	client := UClient(&net.TCPConn{}, &Config{ServerName: serverName, ClientSessionCache: nil}, id)
	if spec != nil {
		if err := client.ApplyPreset(spec); err != nil {
			t.Fatal(err)
		}
	}
	if err := client.BuildHandshakeState(); err != nil {
		t.Fatal(err)
	}
	return client
}

func chrome155CompareWire(t *testing.T, want, got chrome155WireHello) {
	t.Helper()
	if !reflect.DeepEqual(got, want) {
		t.Errorf("generated ClientHello differs from fresh Chrome 155 capture:\n got: %+v\nwant: %+v", got, want)
	}
}

func TestChrome155CapturedClientHello(t *testing.T) {
	if HelloChrome_Auto != HelloChrome_155 {
		t.Fatalf("HelloChrome_Auto = %s, want %s", HelloChrome_Auto.Str(), HelloChrome_155.Str())
	}
	want, _, captured := chrome155ParseWire(t, chrome155Fixture(t))
	client := chrome155Build(t, HelloChrome_155, chrome155FixtureServerName(t, captured), nil)
	got, _, generated := chrome155ParseWire(t, client.HandshakeState.Hello.Raw)
	chrome155CompareWire(t, want, got)
	if ticket, ok := generated[35]; !ok || len(ticket) != 0 {
		t.Fatal("fresh profile must advertise an empty session_ticket extension")
	}
	if _, ok := generated[41]; ok {
		t.Fatal("fresh profile unexpectedly offers pre_shared_key")
	}
}

func TestChrome155DefaultFingerprintRoundTrip(t *testing.T) {
	fixture := chrome155Fixture(t)
	want, wantOrder, raw := chrome155ParseWire(t, fixture)
	spec, err := (&Fingerprinter{}).FingerprintClientHello(fixture)
	if err != nil {
		t.Fatalf("default Fingerprinter must parse captured Chrome 155 ClientHello: %v", err)
	}
	client := chrome155Build(t, HelloCustom, chrome155FixtureServerName(t, raw), spec)
	got, gotOrder, _ := chrome155ParseWire(t, client.HandshakeState.Hello.Raw)
	chrome155CompareWire(t, want, got)
	if !slices.Equal(gotOrder, wantOrder) {
		t.Errorf("fingerprint roundtrip reordered extensions: got %x, want %x", gotOrder, wantOrder)
	}
	if chrome155TrustAnchors(t, spec.Extensions) == nil {
		t.Fatal("fingerprinted trust anchors must use the typed extension")
	}
}

func chrome155TrustAnchors(t *testing.T, extensions []TLSExtension) *TrustAnchorsExtension {
	t.Helper()
	for _, extension := range extensions {
		if anchors, ok := extension.(*TrustAnchorsExtension); ok {
			return anchors
		}
	}
	t.Fatal("missing typed trust_anchors extension")
	return nil
}

func TestChrome155PresetOwnership(t *testing.T) {
	spec, err := UTLSIdToSpec(HelloChrome_155)
	if err != nil {
		t.Fatal(err)
	}
	before := spec.clone()
	first := chrome155Build(t, HelloCustom, "example.com", &spec)
	second := chrome155Build(t, HelloCustom, "example.com", &spec)
	if !reflect.DeepEqual(&spec, before) {
		t.Fatal("ApplyPreset mutated the reusable Chrome 155 preset")
	}
	anchors := chrome155TrustAnchors(t, first.Extensions)
	if len(anchors.TrustAnchorIDs) == 0 || len(anchors.TrustAnchorIDs[0]) == 0 {
		t.Fatal("Chrome 155 capture must contain trust anchor IDs")
	}
	anchors.TrustAnchorIDs[0][0] ^= 0xff
	for _, extension := range first.Extensions {
		switch extension := extension.(type) {
		case *SignatureAlgorithmsExtension:
			extension.SupportedSignatureAlgorithms[0] = PKCS1WithSHA1
		case *SupportedCurvesExtension:
			extension.Curves[0] = CurveP384
		}
	}
	first.HandshakeState.Hello.CipherSuites[0] = TLS_RSA_WITH_AES_256_CBC_SHA
	if !reflect.DeepEqual(&spec, before) {
		t.Fatal("connection mutations leaked into the reusable Chrome 155 preset")
	}
	wantAnchors := chrome155TrustAnchors(t, before.Extensions).TrustAnchorIDs
	if !reflect.DeepEqual(chrome155TrustAnchors(t, second.Extensions).TrustAnchorIDs, wantAnchors) {
		t.Fatal("nested trust anchor mutations leaked between connections")
	}
	later, err := UTLSIdToSpec(HelloChrome_155)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(chrome155TrustAnchors(t, later.Extensions).TrustAnchorIDs, wantAnchors) {
		t.Fatal("trust anchor mutations leaked into future preset instances")
	}
}

func TestChrome155MLDSAHandshake(t *testing.T) {
	if fips140.Version() == "v1.0.0" {
		t.Skip("ML-DSA is unavailable in FIPS 140-3 module v1.0.0")
	}
	for _, tc := range []struct {
		scheme SignatureScheme
		cert   Certificate
	}{
		{MLDSA44, testMLDSA44Cert},
		{MLDSA65, testMLDSA65Cert},
		{MLDSA87, testMLDSA87Cert},
	} {
		t.Run(tc.scheme.String(), func(t *testing.T) {
			clientConfig := testConfigClient.Clone()
			clientConfig.ClientSessionCache = nil
			serverConfig := testConfigServer.Clone()
			serverConfig.MinVersion, serverConfig.MaxVersion = VersionTLS13, VersionTLS13
			serverConfig.Certificates = []Certificate{tc.cert}
			serverConfig.SessionTicketsDisabled = true
			clientConn, serverConn := localPipe(t)
			client, server := UClient(clientConn, clientConfig, HelloChrome_155), Server(serverConn, serverConfig)
			clientResult := make(chan error, 1)
			go func() { clientResult <- client.Handshake() }()
			serverErr := server.Handshake()
			if serverErr != nil {
				serverConn.Close()
			}
			clientErr := <-clientResult
			if clientErr != nil || serverErr != nil {
				t.Fatalf("Chrome 155 ML-DSA handshake: client=%v, server=%v", clientErr, serverErr)
			}
			for _, state := range []ConnectionState{client.ConnectionState(), server.ConnectionState()} {
				if !state.HandshakeComplete || state.Version != VersionTLS13 || state.DidResume {
					t.Fatalf("expected a fresh full TLS 1.3 handshake: %+v", state)
				}
			}
			peer := client.ConnectionState().PeerCertificates
			if len(peer) == 0 {
				t.Fatal("missing verified server certificate")
			}
			if _, ok := peer[0].PublicKey.(*mldsa.PublicKey); !ok {
				t.Fatalf("server public key = %T, want *mldsa.PublicKey", peer[0].PublicKey)
			}
		})
	}
}

func TestChrome155SignatureGREASESeed(t *testing.T) {
	client := UClient(&net.TCPConn{}, &Config{
		ServerName: "example.com",
		Rand:       &incrementingSource{next: 0x81},
	}, HelloChrome_155)
	if err := client.BuildHandshakeState(); err != nil {
		t.Fatal(err)
	}
	// BoringSSL reserves seed slot 7 for signature algorithms, independently
	// of the cipher, group, extension, and version GREASE slots.
	const signatureSeedSlot = 7
	seed := client.greaseSeed[signatureSeedSlot]
	want := (seed & 0xf0) | 0x0a
	want |= want << 8
	if want == GREASE_PLACEHOLDER {
		t.Fatal("deterministic test seed must distinguish generated GREASE from the placeholder")
	}
	_, _, raw := chrome155ParseWire(t, client.HandshakeState.Hello.Raw)
	r := chrome155Reader{t, raw[13], "signature_algorithms"}
	signatures := chrome155Reader{t, r.vector(2), "signature schemes"}
	r.end()
	got := uint16(signatures.number(2))
	if got != want || got == GREASE_PLACEHOLDER {
		t.Fatalf("signature GREASE = %#04x, want %#04x from BoringSSL seed slot 7", got, want)
	}
	if gotState := uint16(client.HandshakeState.Hello.SupportedSignatureAlgorithms[0]); gotState != want {
		t.Fatalf("signature GREASE in handshake state = %#04x, want %#04x", gotState, want)
	}
}

func TestChrome133CapabilitiesPreserved(t *testing.T) {
	client := chrome155Build(t, HelloChrome_133, "example.com", nil)
	_, _, raw := chrome155ParseWire(t, client.HandshakeState.Hello.Raw)
	r := chrome155Reader{t, raw[13], "Chrome 133 signature_algorithms"}
	got := chrome155Uint16s(t, r.vector(2))
	r.end()
	want := []uint16{
		uint16(ECDSAWithP256AndSHA256), uint16(PSSWithSHA256), uint16(PKCS1WithSHA256),
		uint16(ECDSAWithP384AndSHA384), uint16(PSSWithSHA384), uint16(PKCS1WithSHA384),
		uint16(PSSWithSHA512), uint16(PKCS1WithSHA512),
	}
	if !slices.Equal(got, want) {
		t.Fatalf("Chrome 133 signature schemes changed: got %x, want original classical schemes %x", got, want)
	}
	if _, ok := raw[0xca34]; ok {
		t.Fatal("Chrome 155 trust anchor IDs leaked into the Chrome 133 profile")
	}
}
